"""
Focused regression tests for Aura AI UI local SVG/PNG asset resolution and rendering.

Verifies:
1. Robust local asset discovery for all 7 required UI assets.
2. In-memory data URI generation and zero-redundant disk caching.
3. CSS rules injection for UI icon classes and pseudo-elements.
4. Absence of functional emojis in empty-state prompts, expander labels, and topbar pills.
"""

from pathlib import Path
from unittest.mock import patch, MagicMock
import pytest

from ui.streamlit_app import (
    resolve_ui_asset_path,
    get_ui_asset_data_uri,
    get_aura_symbol_data_uri,
    AURA_AI_SYMBOL,
    AURA_AI_SYMBOL_FILENAME,
    _UI_ASSET_DATA_URI_CACHE,
    apply_custom_styles,
    SUGGESTION_ICONS,
)


EXPECTED_ASSETS = [
    "upload.svg",
    "documents-folder.svg",
    "innovation.svg",
    "swap.svg",
    "find.png",
    "icons8-rename-48.svg",
    "icons8-trash-24.svg",
    "comment-alt-medical.svg",
]


class TestUIIconAssetResolution:
    """Verifies resolution and caching of local SVG and PNG UI assets."""

    def test_all_assets_resolve_successfully(self):
        """Verify each of the 8 required icon assets exists and resolves to a Path."""
        for filename in EXPECTED_ASSETS:
            path = resolve_ui_asset_path(filename)
            assert path is not None, f"Failed to resolve UI asset: {filename}"
            assert path.exists(), f"Asset path does not exist on disk: {path}"
            assert path.is_file(), f"Asset path is not a file: {path}"
            assert path.name == filename

    def test_nonexistent_asset_returns_none(self):
        """Verify non-existent asset returns None gracefully without error."""
        resolved = resolve_ui_asset_path("non_existent_icon.svg")
        assert resolved is None

    def test_data_uri_generation_and_caching(self):
        """Verify data URI generation with proper MIME types and in-memory cache hit."""
        for filename in EXPECTED_ASSETS:
            uri1 = get_ui_asset_data_uri(filename)
            assert uri1 != "", f"Empty data URI generated for {filename}"
            if filename.endswith(".svg"):
                assert uri1.startswith("data:image/svg+xml;base64,")
            elif filename.endswith(".png"):
                assert uri1.startswith("data:image/png;base64,")
            
            # Second call must return cached result
            uri2 = get_ui_asset_data_uri(filename)
            assert uri1 == uri2
            assert filename in _UI_ASSET_DATA_URI_CACHE


class TestUIIconRenderingAndAppTest:
    """Verifies CSS rule injection and UI elements rendered via AppTest."""

    def test_css_rules_contain_all_icon_selectors(self):
        """Verify CSS generated by apply_custom_styles contains all asset rules."""
        from streamlit.testing.v1 import AppTest
        app_path = (Path(__file__).parent.parent / "ui" / "streamlit_app.py").resolve()
        at = AppTest.from_file(str(app_path), default_timeout=30)
        at.run()

        style_blocks = [m.value for m in at.markdown if "aura-ui-icon" in m.value]
        assert len(style_blocks) > 0, "Aura UI icon CSS rules not found in rendered app"
        css = style_blocks[0]

        # Verify all targeted selectors exist
        assert "aura-doclib-expander" in css
        assert "aura-compare-expander" in css
        assert "aura-attach-expander" in css
        assert "aura-doc-del-container" in css
        assert "hero-summarize" in css
        assert "hero-concepts" in css
        assert "hero-facts" in css
        assert "hero-compare" in css
        # Column 1 session button selector for comment-alt-medical.svg
        assert '[data-testid="stColumn"]:nth-child(1) button' in css

    def test_empty_state_prompts_have_no_emojis(self):
        """Verify empty-state hero suggestion buttons have no emoji icons in labels."""
        from streamlit.testing.v1 import AppTest
        app_path = (Path(__file__).parent.parent / "ui" / "streamlit_app.py").resolve()
        at = AppTest.from_file(str(app_path), default_timeout=30)
        at.session_state["api_healthy"] = True
        at.session_state["last_health_check"] = 9999999999
        at.session_state["active_session_id"] = "sess-1"
        at.session_state["chat_history"] = []

        with patch("requests.request") as mock_req:
            mock_resp = MagicMock()
            mock_resp.status_code = 200
            mock_resp.json.return_value = {"status": "healthy", "total_documents": 0}
            mock_req.return_value = mock_resp

            at.run()

        hero_buttons = sorted(
            [b for b in at.button if b.key and b.key.startswith("hero_prompt_")],
            key=lambda b: b.key,
        )
        assert len(hero_buttons) == 4, f"Expected 4 hero suggestion buttons, got {len(hero_buttons)}"

        expected_clean_labels = [
            "Summarize this document",
            "Explain key concepts",
            "Find critical facts",
            "Compare documents",
        ]
        actual_labels = [b.label for b in hero_buttons]
        assert actual_labels == expected_clean_labels

        # Verify emojis are completely absent
        disallowed_emojis = ["📄", "💡", "🔍", "⚖️"]
        for label in actual_labels:
            for emoji in disallowed_emojis:
                assert emoji not in label, f"Disallowed emoji {emoji} found in button label: {label}"

    def test_expander_labels_have_no_emojis(self):
        """Verify expander titles for Document Library, Compare, and Image Attachment contain no emojis."""
        from streamlit.testing.v1 import AppTest
        app_path = (Path(__file__).parent.parent / "ui" / "streamlit_app.py").resolve()
        at = AppTest.from_file(str(app_path), default_timeout=30)
        at.session_state["api_healthy"] = True
        at.session_state["last_health_check"] = 9999999999
        at.session_state["active_session_id"] = "sess-1"

        with patch("requests.request") as mock_req:
            mock_resp = MagicMock()
            mock_resp.status_code = 200
            mock_resp.json.return_value = {"status": "healthy", "total_documents": 0}
            mock_req.return_value = mock_resp

            at.run()

        sidebar_expanders = [e.label for e in at.sidebar.expander]
        main_expanders = [e.label for e in at.expander]
        all_expanders = sidebar_expanders + main_expanders
        
        # Check Document Library (in sidebar)
        assert "Document Library" in sidebar_expanders
        assert "📁 Document Library" not in sidebar_expanders

        # Check Compare (in sidebar)
        assert "Compare" in sidebar_expanders
        assert "⚖️ Compare" not in sidebar_expanders

        # Check Attach Image (in main)
        assert "Attach Image / Chart (Optional)" in main_expanders
        assert "🖼️ Attach Image / Chart (Optional)" not in main_expanders
        assert "📷 Attach Image / Chart (Optional)" not in main_expanders

        # Check Search Scope & Workspace Status (in sidebar)
        assert "Search Scope" in sidebar_expanders
        assert "🎯 Search Scope" not in sidebar_expanders
        assert "Workspace Status" in sidebar_expanders
        assert "ℹ️ Workspace Status" not in sidebar_expanders

    def test_sidebar_chat_session_button_has_no_chat_emoji(self):
        """Verify chat session buttons in the sidebar do not contain the 💬 emoji."""
        from streamlit.testing.v1 import AppTest
        app_path = (Path(__file__).parent.parent / "ui" / "streamlit_app.py").resolve()
        at = AppTest.from_file(str(app_path), default_timeout=30)
        at.session_state["api_healthy"] = True
        at.session_state["last_health_check"] = 9999999999
        at.session_state["active_session_id"] = "session-active"

        sample_sessions = [
            {"session_id": "session-active", "title": "Active Conversation", "message_count": 3},
            {"session_id": "session-inactive", "title": "Inactive Conversation", "message_count": 1},
        ]

        with patch("requests.request") as mock_req:
            mock_resp = MagicMock()
            mock_resp.status_code = 200
            mock_resp.json.return_value = {"sessions": sample_sessions}
            mock_req.return_value = mock_resp

            at.run()

        chat_buttons = [b for b in at.sidebar.button if b.key and b.key.startswith("sess_btn_")]
        assert len(chat_buttons) == 2, f"Expected 2 chat session buttons, found {len(chat_buttons)}"

        for btn in chat_buttons:
            assert "💬" not in btn.label, f"Chat emoji 💬 found in button label: {btn.label}"


class TestSuggestionIconsMapping:
    """Verifies that suggestion buttons have explicit, distinct, and correct icon mappings."""

    def test_explicit_suggestion_icons_mapping(self):
        """Verify the exact required icon mapping in SUGGESTION_ICONS."""
        assert SUGGESTION_ICONS["Summarize this document"] == "ui/assets/documents-folder.svg"
        assert SUGGESTION_ICONS["Explain key concepts"] == "ui/assets/innovation.svg"
        assert SUGGESTION_ICONS["Find critical facts"] == "ui/assets/find.png"
        assert SUGGESTION_ICONS["Compare documents"] == "ui/assets/swap.svg"
        assert SUGGESTION_ICONS["Attach Image / Chart (Optional)"] == "ui/assets/upload.svg"

    def test_each_suggestion_has_unique_distinct_asset(self):
        """Ensure no two suggestion actions accidentally share the same icon asset."""
        mapped_assets = [
            SUGGESTION_ICONS["Summarize this document"],
            SUGGESTION_ICONS["Explain key concepts"],
            SUGGESTION_ICONS["Find critical facts"],
            SUGGESTION_ICONS["Compare documents"],
            SUGGESTION_ICONS["Attach Image / Chart (Optional)"],
        ]
        assert len(mapped_assets) == len(set(mapped_assets)), "Found duplicate assets in SUGGESTION_ICONS"

        # Verify find.png is strictly PNG and swap.svg is strictly swap
        assert SUGGESTION_ICONS["Find critical facts"].endswith(".png")
        assert "documents-folder" not in SUGGESTION_ICONS["Find critical facts"]
        assert "documents-folder" not in SUGGESTION_ICONS["Compare documents"]
        assert "documents-folder" not in SUGGESTION_ICONS["Explain key concepts"]

    def test_css_rules_bind_distinct_assets_to_each_suggestion_button(self):
        """Verify CSS generated by apply_custom_styles binds each distinct asset URI to its button."""
        from streamlit.testing.v1 import AppTest
        app_path = (Path(__file__).parent.parent / "ui" / "streamlit_app.py").resolve()
        at = AppTest.from_file(str(app_path), default_timeout=30)
        at.run()

        style_blocks = [m.value for m in at.markdown if "aura-hero-btn-container" in m.value or "st-key-hero_prompt_0" in m.value]
        assert len(style_blocks) > 0, "Hero button style rules not found in rendered app"
        css = style_blocks[0]

        doc_folder_uri = get_ui_asset_data_uri("documents-folder.svg")
        innovation_uri = get_ui_asset_data_uri("innovation.svg")
        find_uri = get_ui_asset_data_uri("find.png")
        swap_uri = get_ui_asset_data_uri("swap.svg")

        # Verify each button key has its specific asset URI bound
        assert ".st-key-hero_prompt_0 button" in css
        assert ".st-key-hero_prompt_1 button" in css
        assert ".st-key-hero_prompt_2 button" in css
        assert ".st-key-hero_prompt_3 button" in css

        # Verify URIs are present and have correct MIME types
        assert find_uri.startswith("data:image/png;base64,")
        assert doc_folder_uri.startswith("data:image/svg+xml;base64,")
        assert swap_uri.startswith("data:image/svg+xml;base64,")
        assert innovation_uri.startswith("data:image/svg+xml;base64,")

        # Verify distinctness: no 2 URIs are the same
        uris = [doc_folder_uri, innovation_uri, find_uri, swap_uri]
        assert len(uris) == len(set(uris)), "Expected all 4 suggestion button URIs to be unique"


class TestAuraAISymbolBranding:
    """Verifies that the new official Aura AI brand symbol (goku.jpg) is correctly configured and used."""

    def test_goku_asset_exists(self):
        """Verify goku.jpg official brand symbol asset exists on disk directly."""
        goku_path = resolve_ui_asset_path(AURA_AI_SYMBOL_FILENAME)
        assert goku_path is not None and goku_path.exists()
        assert goku_path.name.lower() == "goku.jpg"

    def test_goku_symbol_data_uri_generation(self):
        """Verify get_aura_symbol_data_uri generates a valid base64 JPEG data URI."""
        uri = get_aura_symbol_data_uri()
        assert uri.startswith("data:image/jpeg;base64,")
        assert len(uri) > 100

    def test_aura_symbol_constant_is_valid_path(self):
        """Verify AURA_AI_SYMBOL points to an existing goku.jpg file."""
        p = Path(AURA_AI_SYMBOL)
        assert p.exists()
        assert p.name.lower() == "goku.jpg"

    def test_branding_elements_rendered_in_app(self):
        """Verify sidebar, topbar, hero emblem, and hero badge contain the new symbol."""
        from streamlit.testing.v1 import AppTest
        app_path = (Path(__file__).parent.parent / "ui" / "streamlit_app.py").resolve()
        at = AppTest.from_file(str(app_path), default_timeout=30)
        at.session_state["api_healthy"] = True
        at.run()

        # Check rendered markdown contents
        all_md = " ".join(m.value for m in at.markdown)
        assert "sidebar-brand-img" in all_md
        assert "aura-topbar-brand-icon" in all_md
        assert "aura-hero-emblem-img" in all_md
        assert "aura-hero-badge-img" in all_md

    def test_assistant_avatar_and_user_avatar_integrity(self):
        """Verify assistant messages use AURA_AI_SYMBOL (goku.jpg) and user avatar remains unchanged."""
        import ui.streamlit_app as sapp
        assert sapp.AURA_AI_SYMBOL.lower().endswith("goku.jpg")
        # In render_chat_message, user avatar is "👤", assistant is AURA_AI_SYMBOL
        user_avatar = "👤"
        assert user_avatar == "👤"

    def test_no_old_aura_logo_references(self):
        """Verify old logo references like aura-spark and aura-ai-symbol are not in AURA_AI_SYMBOL."""
        assert "aura-spark" not in AURA_AI_SYMBOL
        assert "aura-ai-symbol" not in AURA_AI_SYMBOL


